### ISSUE TITLE
페이지 렌더

### ISSUE THREAD

**Issue by SJLEE316** [bwbluemove/bluemove-portal#4]
https://user-images.githubusercontent.com/65484500/147937308-4e8260fd-5830-46be-9df6-c05d3c104feb.mp4

## 현재상황
- 영상보면 '명부에 없는 회원입니다.' alert 창 뜨고 탈퇴페이지에서 메인페이지로 이동함

## 이상적인 구현방식
- alert 창 뜨고 (탈퇴페이지 거치지 않고) 메인페이지로 리다이렉트 시키고 싶음. 미관상 마음에 안들어,,,
- redirect로 하자니 alert를 띄울 방법을 모르겠ㅇ,,,

## 문제점( = 나의 개발실력 부족...)
- alert 창을 띄우려니까 자바스크립트를 써야함. 
- 자바스크립트 코드는 탈퇴페이지에 있음

```python
def leavenow(request):
    ...
        if (i == bm-1 and count == 0) :
            result = '명부에 없는 회원입니다.'
            return render(request, 'applynsubmit/leavemembership.html', {"result" : result})
    
    ...

    result = '정상적으로 탈퇴되었습니다. 다음에 좋은 인연으로 다시 만나요!'
    return render(request, 'applynsubmit/leavemembership.html', {"result" : result})

```

- view에서 회원없음 or 탈퇴성공 확인 -> 탈퇴페이지로 render ( result도 같이 render) -> 탈퇴페이지로 이동해서 자바스크립트 코드 실행 (alert실행되고 [탈퇴페이지 잠깐 나왔다가] 메인페이지로 이동)
- 장고 실력 부족으로 자바스크립트로 페이지 이동을 구현한 상태. 

***alert띄우고 페이지 이동을 모두 이따구로 구현한 상태.. 아이디어 있으면 코멘트 주세요 :)***

**Comment by bluemove-yomin** [comment]
그동안 블뭅포털 만들면서 주로 썼던 방법으로 하자면
1. views.py에서 leavenow 함수 상단에 불리언 용도의 빈 변수 생성
`left = None`
2. leavenow 함수에서 탈퇴 코드 바로 아래에 해당 불리언을 True로 설정
→ 유저 입장에선 "진짜 탈퇴할거야?"라는 js confirm에서 Yes 누른 직후
`left = True`
3. render를 탈퇴 페이지로 하지 말고 메인 페이지로 한 다음 메인 페이지에 left 넘기기
`return render(request, "home/main.html", {"left" : left})`
4. 메인 페이지 html에 장고 템플릿 태그로 {% if left %} ~~~ {% endif %} 넣고
5. 템플릿 태그 사이에는 원하는 alert가 DOM 최우선 순위로 나오게 코드 작성

요렇게 하면 원하는 대로 흰 바탕에 alert 뜨고 바로 메인 페이지 뜨려나요?

**Comment by SJLEE316** [comment]
애초에 url은 leavenow로 했는데 페이지는 home/main으로 렌더하면
url은 /leavnow인데 보이는 화면은 main인 상황인데 상관 없을까요?

**Comment by bluemove-yomin** [comment]
그러면 렌더를 하지 말고 파라미터와 함께 home:main으로 리다이렉트를 한 다음 (예를 들면 example.com/?left)
home:main 템플릿 html에서 {% if "left=" in request.get_full_path %} ~ {% endif %} 이런 템플릿 태그 안에 JS alert 스크립트를 넣으면 어떨까요?

### UPDATE
2022-02-01 다시 짜기로 함. 클로즈.
